### ISSUE TITLE
TG API Throttle

### ISSUE THREAD

**Issue by pouling** [ail-project/ail-feeder-telegram#3]
Try to run the command python3 feeder.py --getall
everything start, but after a while I start seeing error like that

ERROR [api.py:116 - _check_response() ] Something went wrong (401): {'reason': 'Max Connection Attempts reached, Please wait 299s', 'status': 'error'}

and it crash after saying this

-752095614
Traceback (most recent call last):
  File "feeder.py", line 155, in <module>
    client.loop.run_until_complete(get_entity_messages(client, entity, min_id=min_id, max_id=max_id))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "feeder.py", line 77, in get_entity_messages
    await telegram.get_all_channel_messages(client, entity, pyail, min_id=min_id, max_id=max_id, feeder_uuid=feeder_uuid)
  File "/home/********/ail-feeder-telegram/bin/telegram.py", line 199, in get_all_channel_messages
    dict_meta['channel_id'] = message.input_chat.channel_id
AttributeError: 'InputPeerChat' object has no attribute 'channel_id'

**Comment by oencarnacion** [comment]
Same problem, any news? @pouling
